excerpt_separator: ""
markdown: kramdown
permalink: pretty
highlighter: rouge

paginate: 10
paginate_path: "/page/:num"
url: https://walez.github.io
name: Martins Wale
description: Software development Journey
author: Wale
# A short presentation of yourself. Will show in the sidebar, under your name. Best usage would be between 30 to 50 words.
author-bio: "I'm a software developer. I develop things mainly in Javascript other times with PHP and somethings in Java"
avatar: http://www.gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e?s=120&d=mm&r=g
ga_domain: auto
ga_tracking_id: UA-96553874-1

# Social Accounts (mine, as placeholders)

twitter: wale_martin
github: walez
instagram: walez18
email: martinsadewalehakeem@gmail.com

# SCSS

sass:
  sass_dir: _scss
  style: :compressed

gems: [jekyll-paginate]
